version: "3.4"

services:

  jasmine-service:
    image: jboss/wildfly
    container_name: jasmine-service-dev
    hostname: jasmine-service-dev
    depends_on:
      - jasmine-database
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ./docker/wildfly/.bin/:/opt/jboss/.bin/
    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /opt/jboss/.bin/*.sh && /opt/jboss/.bin/entrypoint.sh"
    ]

  jasmine-database:
    image: mysql:5.7
    container_name: jasmine-db-dev
    hostname: jasmine-db-dev
    ports:
      - "3306:3306"
    env_file:
      - .env.dev
