version: "3.4"

services:

  jasmine-service:
    image: jboss/wildfly
    container_name: jasmine-service-dev
    hostname: jasmine-service-dev
    depends_on:
      - jasmine-database
    ports:
      - "8080:8080"
    env_file:
      - docker/.env-database
    volumes:
      - ./docker/wildfly/bin/:/opt/jboss/dist/bin/
      - ./dist/:/opt/jboss/dist/delivery/
    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /opt/jboss/dist/bin/*.sh && /opt/jboss/dist/bin/entrypoint.sh"
    ]

  jasmine-database:
    image: mysql:5.7
    container_name: jasmine-db-dev
    hostname: jasmine-db-dev
    ports:
      - "3306:3306"
    env_file:
      - docker/.env-database
