version: "3.4"

services:

  jasmine-service:
    image: jboss/wildfly:11.0.0.Final
    container_name: jasmine-service-dev
    hostname: jasmine-service-dev
    depends_on:
      - jasmine-database
    ports:
      - "8080:8080"
    env_file:
      - docker/.env-database
    volumes:
      - ${PWD}/docker/wildfly/bin/:/opt/jboss/dist/bin/
      - ${PWD}/sources/jasmine/jasmine-server/target/jasmine.war:/opt/jboss/dist/delivery/jasmine.war
    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /opt/jboss/dist/bin/*.sh && /opt/jboss/dist/bin/entrypoint.sh"
    ]

  jasmine-database:
    image: postgres:10.1
    container_name: jasmine-db-dev
    hostname: jasmine-db-dev
    ports:
      - "5432:5432"
    env_file:
      - docker/.env-database
